### PR TITLE
Support rails 5.0.x and active_model 5.0.x

### PR DESCRIPTION
**Pull request by gastzars**
I have changed dependency version to support rails 5.0.x

### CODE REVIEW

**Comment by cavi21** [comment]
Hey guys! any idea when this could be merge? I know that you where very busy the couple of months when you started maintain this project and you are doing an incredible job! thanks a LOT for it! 👍 🙇 

I believe that this PR covers the comments of @bglusman on the other to PRs #101 and #92 and maybe other ones.

Can we help on anything? again thanks!

**Comment by bglusman** [comment]
@cavi21 Thanks!  this looks good to me now, @pboling any concerns? I'll plan to merge later today or maybe over the weekend if I don't hear otherwise.

**Comment by pboling** [comment]
Looks good to me!

**Comment by danlelandsuarez** [comment]
Was this supposed to handle creation of the tables when they do not exist yet?

**Pull request merged**
