### PR TITLE
Reprocess keys for composite key tables in BatchGetItem

### PR DESCRIPTION
**Pull request by Bajena**
closes https://github.com/Dynamoid/dynamoid/issues/510

### CODE REVIEW

**Comment by andrykonchin** [comment]
Looks pretty good 👍 Thank you for the fix.

**Comment by Bajena** [comment]
Thanks @andrykonchin! Hope you had a nice vacation :)
Do you think you'd be able to release a patch version (3.7.1) with yesterday's fix?

**Comment by andrykonchin** [comment]
Yes, sure.

**Comment by Bajena** [comment]
@andrykonchin Ping :)

**Comment by andrykonchin** [comment]
The new version is released 🎆

**Comment by Bajena** [comment]
Thank you @andrykonchin!

**Pull request merged**
