### PR TITLE
Fix problems with range query

### PR DESCRIPTION
**Pull request by ayemos**
https://github.com/Dynamoid/Dynamoid/issues/41

Now it works with query like
```ruby
class SomeModel
  include Dynamoid::Document

  table :name => :some_table, key: :some_hash_id

  range :some_range_id, :string

...

SomeModel.where(some_hash_id: 100,
'some_range_id.gt': 'abcd', 'some_range_id.lt': 'abxy').all


```

Please review :bow:
(@ananthakumaran : You may be the best one)

### CODE REVIEW

**Comment by philipmw** [comment]
Thanks! It looks good. Can you squash your commits?

**Comment by ayemos** [comment]
> Thanks! It looks good. Can you squash your commits?

I did it.

**Comment by ayemos** [comment]
I found that API will regard multiple {gt, lt}, conditions as 'OR' query.

[AdapterPlugin::AwsSdkV2](https://github.com/Dynamoid/Dynamoid/blob/master/lib/dynamoid/adapter_plugin/aws_sdk_v2.rb#L264)
supports range_between option on query method but it's not set within criteria chain at all.

I'll let it supports 'range_between' options by next commit.

**Comment by ayemos** [comment]
Is CI working properly? Maybe some problems with DynamoDBLocal or something...

**Comment by philipmw** [comment]
Thanks!

**Comment by ruslankhaertdinov** [comment]
It helps me a lot 👍

**Pull request merged**
