### PR TITLE
add active support load hooks

### PR DESCRIPTION
**Pull request by aaronmallen**
Add `ActiveSupport` load hook on `Dynamoid::Document` load

### CODE REVIEW

**Comment by andrykonchin** [comment]
Looks good. Can you add some specs?

**Comment by aaronmallen** [comment]
> Looks good. Can you add some specs?

Sorry, this is serious or a joke request?

**Comment by aaronmallen** [comment]
I'm not sure how to go about writing a spec for this... I looked through rails/rails and heartcombo/devise to see how they may have tested it and they don't.  The problem being when `spec_helper` is loaded `Dynamoid::Document` is already loaded so there isn't away I'm aware of to spy on `ActiveSupport` before this happens.  I could try to unload `Dynomoid::Document` and re-require it but I'm not sure what kind of side effects that would introduce to the spec.  Do you have any suggestions on what kind of spec you'd like to see here?

**Comment by andrykonchin** [comment]
If I understand correctly the source code here

https://github.com/rails/rails/blob/6-0-stable/activesupport/lib/active_support/lazy_load_hooks.rb#L41-L54

registering a new hook (with `on_load`) even when `run_load_hooks` method call already happened still runs new hook. So it could be tested this way - register a hook and checking it was immediately called.

I am afraid if there is no any proper test this functionality could be easily broken/removed in Dynamoid without understanding what it is.

**Comment by andrykonchin** [comment]
Looks good 👍 
Thanks

**Pull request merged**
