### PR TITLE
Raw datatype

### PR DESCRIPTION
**Pull request by psergus**
we really needed native type that picks up existing models on DynamoDB. AWS's SDK V2 already has a support for persisting datatypes to dynamo, so why not utilize it.

### CODE REVIEW

**Comment by tadast** [comment]
This looks like a great addition. Apart from rebasing and adding some documentation, is there anything else that's preventing this from getting merged?

**Comment by psergus** [comment]
thx @tadast, should I rebase and we can merge?

**Comment by pboling** [comment]
Please rebase on latest master - Spec suite is fixed!!!

**Comment by psergus** [comment]
closing in favor for https://github.com/Dynamoid/Dynamoid/pull/104

**Pull request closed without merging**
