### PR TITLE
Feature: Add scope

### PR DESCRIPTION
**Pull request by baloran**
I'm gonna implement scope, default_scope. My code gonna be full inspired by how mongoid made it.

# Features
- [ ] Add scope
- [ ] Add default_scope

I add information about this PR during I code this.

### CODE REVIEW

**Comment by andrykonchin** [comment]
I don't see any changes

**Comment by baloran** [comment]
@andrykonchin I'm gonna push. Not finished yet.

**Comment by amcmillion** [comment]
Any traction on this? It would be great to be able to write quick scopes against our dynamoid models!

**Comment by andrykonchin** [comment]
Looks like no. This feature is in the roadmap so will be released in nearest future.

**Pull request closed without merging**
