### PR TITLE
Support range key in secondary index queries

### LINKED ISSUE #75: Support additional options for find_all_by_secondary_index
From TODO in code:
```
      # @param [Hash] options - @TODO support more options in future such as
      #               query filter, projected keys etc
```

### PR DESCRIPTION
**Pull request by pboling**
Fixed #75 
CC @bglusman

### CODE REVIEW

**Comment by pboling** [comment]
@philipmw I think this spec failure is bogus, and I think I see a lot of similar failures.  Is the spec suite prone to intermittent failures?
@bglusman what do you think of this change?

**Comment by cavi21** [comment]
Hey @pboling I tried to fix this situation with the specs and after a bunch of testing and checking narrow it down to to some situation on the travis-ci images limits. I also download and run everything in a local docker image (as if it's a Travis-CI run) and could not reproduce the error in a consistent way. 

Let me know if you have any other idea and I will love and happy to give it a chance!

(Also FYI I'm not a member of the project, so as you, just a collaborator)

**Comment by pboling** [comment]
@philipmw - Any thoughts?  I think this is ready to merge.  I think the build failure is BS.

**Comment by pboling** [comment]
@philipmw bump

**Comment by pboling** [comment]
FYI - for those watching: This is working in production.  My fork has all the fixes I am using, including this one.

**Pull request closed without merging**
