### PR TITLE
Added a bang version of the `update` class method

### PR DESCRIPTION
**Pull request by UrsaDK**
This PR adds a missing bang version of the `update` class method, eg: `Post.update!(101, title: 'New title')`

### CODE REVIEW

**Comment by andrykonchin** [comment]
Looks good.

Could you add specs [here](https://github.com/Dynamoid/dynamoid/blob/master/spec/dynamoid/persistence_spec.rb#L823)?

**Comment by UrsaDK** [comment]
Sure! Though, I'm a bit swamped at the moment, so it might have to wait 'till the weekend / early next week.

I'll update this PR once the tests are in place.

**Comment by UrsaDK** [comment]
@andrykonchin, I finally found a bit of time to have a look at those tests. I've modelled them on the existing tests for `update`, but added a test to ensure that `update!` with an invalid record raises `Dynamoid::Errors::DocumentNotValid`.

The tests pass locally (1051 examples, 0 failures, 13 pending) but travis is reporting a build failure (not sure what's going on there).

Let me know if you want me to change anything else.

**Comment by andrykonchin** [comment]
Looks good 👍. Thank you.

**Pull request merged**
